### ISSUE TITLE
Update questions

### ISSUE THREAD

**Issue by Ghost-Cavendish** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#1]
Hello, brother, will you continue to update later

**Comment by b00t0x** [comment]
Yes, I'm testing intermittently, but I'm having a hard time solving [the issues listed in the README](https://github.com/b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh/blob/main/README.md#not-working--problems).

I'm going to create github issues to describe details and status, and I hope someone to help to solve the issues.
