### ISSUE TITLE
Instant KP Kernel Extensions in backtrace: com.apple.driver.AppleACPIPlatform

### ISSUE THREAD

**Issue by AmElvy** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#10]
![IMG_20221120_165318](https://user-images.githubusercontent.com/59524073/202888122-02770eb9-c26b-4655-9606-08b4f40400d6.jpg)
I downloaded Monterey, copied everything and generated a smbios. Now I get a instant kp and I'm not sure how to proceed. Sorry if this is obvious, it's my first hackintosh in years

**Comment by ExtremeXT** [comment]
> ![IMG_20221120_165318](https://user-images.githubusercontent.com/59524073/202888122-02770eb9-c26b-4655-9606-08b4f40400d6.jpg) I downloaded Monterey, copied everything and generated a smbios. Now I get a instant kp and I'm not sure how to proceed. Sorry if this is obvious, it's my first hackintosh in years

Reinstall vanilla Monterey and update your kernel patches, you don't need to modify IOPCIFamilly and AppleACPIPlatform anymore.

**Comment by AmElvy** [comment]
> > ![IMG_20221120_165318](https://user-images.githubusercontent.com/59524073/202888122-02770eb9-c26b-4655-9606-08b4f40400d6.jpg) I downloaded Monterey, copied everything and generated a smbios. Now I get a instant kp and I'm not sure how to proceed. Sorry if this is obvious, it's my first hackintosh in years
> 
> Reinstall vanilla Monterey and update your kernel patches, you don't need to modify IOPCIFamilly and AppleACPIPlatform anymore.

I tried updating the amd osx patches but it still kp. I tried recreating config.plist but it just reboots while trying to load the dmg. 
i don't know what i'm doing wrong, any advice?

**Comment by ExtremeXT** [comment]
> > > ![IMG_20221120_165318](https://user-images.githubusercontent.com/59524073/202888122-02770eb9-c26b-4655-9606-08b4f40400d6.jpg) I downloaded Monterey, copied everything and generated a smbios. Now I get a instant kp and I'm not sure how to proceed. Sorry if this is obvious, it's my first hackintosh in years
> > 
> > 
> > Reinstall vanilla Monterey and update your kernel patches, you don't need to modify IOPCIFamilly and AppleACPIPlatform anymore.
> 
> I tried updating the amd osx patches but it still kp. I tried recreating config.plist but it just reboots while trying to load the dmg. i don't know what i'm doing wrong, any advice?

Do you have Discord or Telegram?

**Comment by AmElvy** [comment]
> Do you have Discord or Telegram?

My discord is NotC#6952

**Comment by b00t0x** [comment]
I have problems in BIOS version 315, so if you run in this BIOS try downgrading to version 312.
