### ISSUE TITLE
Help; "AAPL: #[EB|LOG:EXITBS:START]" stuck issue TT

### ISSUE THREAD

**Issue by joonPM** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#14]
Hi
I have a ROG Zephyrus G14 2022 (GA402RJ) and just happened to see this post from you so I tried Hackin but it keeps stopping at 30% of the Apple logo.
Additionally, if you look at the debug file, AAPL: #[EB|LOG:EXITBS:START] is printed

The parts that are different from yours are as follows

My laptop specs
CPU - Ryzen 9 6900hs
SSD - WD SN735 512gb
WiFi - original MediaTek M.2 2230 card

Except for the cpu, ssd, wifi modules, I did the same as the bios version and macos version you talked about and used your efi

I've been going around the internet for a few days to solve this part, but I haven't So lastly, I ask you for help

https://drive.google.com/file/d/1Ee1iBOO-lYxbe5D7YZEKUmis6U5cW93r/view?usp=share_link

**Comment by b00t0x** [comment]
disable wifi and bt kexts, and try to set your own MmioWhitelist by follow this guide.
https://dortania.github.io/OpenCore-Install-Guide/extras/kaslr-fix.html#using-devirtualisemmio

**Comment by joonPM** [comment]
Thank you for the answer. :)
I'll try the solution you told me about.
And I have a question, is the reason why I stop at 30% of Apple logo is because the wifi & bt module is different from yours?
