### ISSUE TITLE
CPU not fully utilized during all-core load

### ISSUE THREAD

**Issue by nocchijiang** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#17]
As title said.

At first i thought this could a power limit issue, so i set all power limit to 80W using ryzenadj. Unfortunately CPU still only draws 34W during all-core load (reported by AMD Power Gadget).

**Comment by nocchijiang** [comment]
Update: After setting `--apu-slow-limit` to `1250000` CPU can finally draw more than 34W, however it is thermal throttled now (96C all the time). I think the fan curve is not reflecting the settings i used in Windows (ultimate in armoury crate).

**Comment by b00t0x** [comment]
I haven't explored performance yet, but GPU power management doesn't seem to work on this build, so I'm guessing that GPU heat is throttling the CPU power.
( This PC has a dGPU, but the cooling components are shared by the CPU and dGPU. )

**Comment by nocchijiang** [comment]
Thanks for your reply!

I think that dGPU is not affecting the thermals that much. From my personal feeling (comparing the fan noise between Windows and MacOS) I still think it is a fan curve issue. The fan is definitely louder in Windows when setting performance profile to Ultimate in Armoury Crate and CPU can draw ~60W during an extended load; ~53W in MacOS after applying `--apu-slow-limit=125000`, although it is fair to say that 7W won't bring that much difference in terms of performance. One other thing I noticed is that the settings applied with `ryzenadj` will be reset when awaken up from sleep.

Btw this machine actually feels painfully slower compared to my Apple Silicon MacBook Pro. I am working on a patch and testing a debug build of Swift, which needs more than 1 hour to finish the bootstrapping steps (single-threaded) on this hackintosh. On the Apple Silicon MacBook Pro the same steps takes no more than 10 minutes. Guess something else is wrong because the thermal should not be a problem for single-threaded tasks.

**Comment by nocchijiang** [comment]
<img width="413" alt="image" src="https://github.com/b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh/assets/9026760/2adf59d9-4aea-43fb-ab85-926f2bac69dc">

After updating to the latest version from your August updates the CPU can now run at 96C with 60W power draw. I think some changes affect the fan curve to allow it to spin at the fastest speed.

BTW, may I ask why did you choose MacPro7,1 for smbios? Or have you tried something like iMac17,1 or so? I want to enable Sidecar for the system, and the only possible solution seems to be an iMac smbios for AMD dGPU-only systems.
