### ISSUE TITLE
USB有点问题 很卡 断断续续 而且键盘也是走USB通道 键盘延迟非常高

### ISSUE THREAD

**Issue by Pan-Jun-Jie** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#18]

**Comment by b00t0x** [comment]
I've been facing that issue since BIOS 315 and still have to use BIOS 312.

**Comment by Pan-Jun-Jie** [comment]
华硕官网已经没有312的bios了 在哪里可以找到

**Comment by b00t0x** [comment]
@Pan-Jun-Jie 
https://web.archive.org/web/20220902061719/https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/BIOS/106920/GA402RJAS312.zip
