### ISSUE TITLE
Guide? (suggestion)

### ISSUE THREAD

**Issue by bruno-cassina** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#20]
This is not an issue, but a suggestion. 
I am new to all of this, but i do really want MacOS on my G-14. Is it possible for a guide of sorts? Thank you.

**Comment by bruno-cassina** [comment]
I loaded all the files onto a GPT partitioned USB but the macos efi dosent show up

**Comment by xzn** [comment]
There's Dortania guide you can find online. It's easier to get a macOS USB ready if you already have a macOS installation to create the USB installation drive

**Comment by bruno-cassina** [comment]
Thank you for the recomendation, but i seem to be getting what is referred to as a "panic". When i am done with the compilation of the usb with macOS Monterey 12.6.8 (21G725) and i upload this repository's files with an updated config.plist and boot into the "Install MacOS Monterey" partition, I get a screen that says "support.apple.com/mac/startup" and I have no idea what I did wrong. Is there any way you could help me? Hints or tips as to common issues you resolved or a way to read output of the boot to find the issue?
