### ISSUE TITLE
感谢你提供的EFI文件，请问可以再提供一下312版本的BIOS固件吗？

### ISSUE THREAD

**Issue by Inzexy** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#23]

**Comment by b00t0x** [comment]
@Inzexy You can download the old bios from here.
https://web.archive.org/web/20220928185508/https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g14-2022-series/helpdesk_bios/
https://web.archive.org/web/20220902061719mp_/https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/BIOS/106920/GA402RJAS312.zip
