### ISSUE TITLE
macOS stopped booting up after replacing WiFi card with Intel one

### ISSUE THREAD

**Issue by wiencheck** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#26]
As the title says I replaced the MediaTek card with Intel, installed drivers on Windows and everything works on that side but the macOS stopped booting up. It goes to the loading bar screen, the bar gets filled to around 50% and then the screen goes black.

Any suggestions? Should I modify something in the EFI?

**Comment by JustARegularXbox** [comment]
What might have happened is you turned off exclusive dGPU mode, and that's probably why it hangs at about 50%.
What you can do however, if that's not the problem, is to turn on verbose booting by going to the config.plist and editing it with propertree under NVRAM boot-args add -v and send here the moment it goes to a black screen.

**Comment by wiencheck** [comment]
Thanks for your response.
The problem went away, I inserted the original card back to check if I didn't mess anything up. When it booted up I updated my EFI with kexts for Intel wifi and after inserting the Intel card again I could boot into macOS.
