### ISSUE TITLE
Ventura support

### ISSUE THREAD

**Issue by b00t0x** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#3]
## Summary
<img width="1280" alt="Screenshot 2022-07-18 at 3 58 33" src="https://user-images.githubusercontent.com/2325377/179477213-a59125fe-3573-4d08-baa0-13a019fdc657.png">

I already manage to boot Ventura but currently complicated steps below are needed.

1. Setup Ventura with the another machine
2. Install Ventura KDK
3. Replace IOPCIFamily.kext and AppleACPIPlatform.kext wiht Big Sur's one
4. Replace many other kexts with Monterey's one
5. Install SSD to GA402 from the another machine

I want to simplify the install process and stop using Big Sur kexts.

Solving #2 may also leads to solve this issue, but I don't know how to fix now.

## Status
- [x] Boot Ventura with heavy replacement of system kexts
- [x] Run Ventura installer on GA402
- [x] Install Ventura on GA402
- [x] Boot Ventura with vanilla system kexts

**Comment by alanxurox** [comment]
Ok to repost in r/hackintosh(ja) or pcbeta(chinese hackintosh)?

**Comment by b00t0x** [comment]
@alanxurox Of course ok. Let me know urls if you repost.

**Comment by b00t0x** [comment]
Kexts from Big Sur (11.6.8) :
- AppleACPIPlatform.kext
- IOPCIFamily.kext

Kexts from Monterey (12.5) :
- AppleBCMWLANBusInterfacePCIeMac.kext
- AppleBCMWLANCoreMac.kext
- AppleOLYHALMac.kext
- AppleVirtIO.kext
- IO80211Family.kext
- IOUSBHostFamily.kext

Deleted kexts :
- IOUSBHostFamily.kext/Contents/PlugIns/AppleUSBRecoveryHost.kext
- IOUSBHostFamily.kext/Contents/PlugIns/AppleUSBVHCIRSM.kext

**Comment by Mrcoolawesome** [comment]
Let's go great job!!
