### ISSUE TITLE
Can't boot

### ISSUE THREAD

**Issue by KristianApostolov** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#4]
Hi, 

I have the same laptop and already swapped the Micron SSD (didn't know if it's going to work). 
I cannot boot...can I contact you somehow?

**Comment by Boris-Karamanolev** [comment]
Using Big Sur by the way. And we get the support.apple.com/startup

**Comment by b00t0x** [comment]
@CrisCodesCrap Are you using a PCIe 4.0 SSD? PCIe 3.0 SSDs are not visible in Monterey Installer.
And using `-v` boot arg to find out what error happens.

**Comment by Boris-Karamanolev** [comment]
We made it too Monterey. The only issues now are watt consumption/hot as well as audio and trackpad. Ive been doing some research on the Trackpad and there are some SSDTs for ETPD (Elan) but they don't seem to work. I found a kext that simulates a mouse but we haven't tried that yet. Is there any way to disable AMD turbo core in macOS?

**Comment by Boris-Karamanolev** [comment]
@b00t0x

**Comment by b00t0x** [comment]
I also research on the Trackpad but no luck now.
CPU boost is already controllable with AMD Power Gadget and ryzenadj command. But power consumption problem doesn't seem CPU problem but dGPU.
