### ISSUE TITLE
Trackpad working

### ISSUE THREAD

**Issue by b00t0x** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#5]
## Summary
Currently the trackpad doesn't work at all.

The trackpad is connected under I2C controller but [VoodooI2C](https://github.com/VoodooI2C/VoodooI2C) doesn't work with AMD I2C controller.
I'm working on [this branch](https://github.com/b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh/tree/voodooi2c) to enable trackpad, but no result so far.

**Comment by b00t0x** [comment]
VoodooI2CACPIController is attached to the controller with [this commit](https://github.com/b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh/commit/457355ba38c7bf9ea84b641b1946b155501c44a1), but the trackpad doesn't work because VoodooI2CHID or VoodooI2CELAN don't attach to VoodooI2CDeviceNub.

<img width="234" alt="キャプチャ 2022-07-30 18 08 55" src="https://user-images.githubusercontent.com/2325377/181903759-9f640aee-c46f-4986-8c35-89772b541a0e.png">

[ioreg-i2c1.zip](https://github.com/b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh/files/9225879/ioreg-i2c1.zip)

**Comment by b00t0x** [comment]
I tried to fix GPIO pinning, but `_CRS` method of the [DSDT](https://github.com/b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh/blob/main/ACPI-origin/DSDT.aml) seems no fix required.
```
            Method (_CRS, 0, Serialized)  // _CRS: Current Resource Settings
            {
                Name (SBFI, ResourceTemplate ()
                {
                    I2cSerialBusV2 (0x0015, ControllerInitiated, 0x00061A80,
                        AddressingMode7Bit, "\\_SB.I2CB",
                        0x00, ResourceConsumer, , Exclusive,
                        )
                    GpioInt (Level, ActiveLow, Exclusive, PullUp, 0x0000,
                        "\\_SB.GPIO", 0x00, ResourceConsumer, ,
                        )
                        {   // Pin list
                            0x0008
                        }
                })
                Return (SBFI) /* \_SB_.I2CB.ETPD._CRS.SBFI */
            }
```
(And rename `GPIO` to `GPI0` made no effects.)

**Comment by Boris-Karamanolev** [comment]
+

**Comment by Babyyoda777** [comment]
Have you tried setting in force polling? Also try downgrading VoodooI2C to v2.6.5

**Comment by b00t0x** [comment]
I tried both `-vi2c-force-polling` and v2.6.5 but unfortunately no effect.

**Comment by swockan** [comment]
I'm not a dev and knows nothing about this, just stumbled upon your project but maybe you can adapt code from Linux MP2 driver for AMD? I think this is used for trackpad etc. Fusion sensor hub or something like that. You can also use universalamdformbrowser to switch between two different firmwares for MP2 in bios and set dgpu to always primary without the need for Windows or armorcrate with this modtool. This tool works for GA402. I apologize if I didn't contributed with something useful. Fun project!

**Comment by alexjaixd** [comment]
Hey @b00t0x have you tried this fork of VoodooI2C from the same devs of Whateverred? It's got something to do with adding AMD i2C support in some of its latest commits apparently. Unfortunately will need some compiling work to make it into a kext so I haven't tried it yet. 

https://github.com/NootInc/VoodooI2C

**Comment by kymerea** [comment]
> Hey @b00t0x have you tried this fork of VoodooI2C from the same devs of Whateverred? It's got something to do with adding AMD i2C support in some of its latest commits apparently. Unfortunately will need some compiling work to make it into a kext so I haven't tried it yet.
> 
> https://github.com/NootInc/VoodooI2C

That's literally what he is using....

**Comment by Zeroaim-exe** [comment]
any news regarding the trackpad?

i just bought a Zephyrus G14 2022 and being able to install and use MacOS would be amazing. Ive build several Hackintoshs back in the day with Clover and Sierra but on Desktop PCs.
I could work with every compromise like keyboard led control and all the other stuff but the trackpad is kind of a dealbreaker for me.

**Comment by Mrcoolawesome** [comment]
Are you still working on this, if not that's understandable and totally fine but it would be great if you did. This is my first hackintosh and it's the coolest thing ever. I found [this](https://github.com/AMD-OSX/AMD_Vanilla) while trying to find fixes for installing Ventura and fixing the trackpad, maybe it could help.

**Comment by xzn** [comment]
Noot's [VoodooI2C](https://github.com/NootInc/VoodooI2C) has some new commits since then that made polling mode work. Need `VoodooI2C.kext` and `VoodooI2CHID.kext` then add `-vi2c-force-pollin` to `boot-arg`

For some reason dragging-without-drag-lock behaves like with-drag-lock, otherwise everything seems to work

**Comment by b00t0x** [comment]
@alexjaixd @xzn I compiled NootInc's VoodooI2C and get the trackpad working. Thank you for the suggestion.

**Comment by RoboCrafty** [comment]
Great! Do all the gestures and everything worked perfectly? If you don’t mind, could you share a video of switching between different desktops and using all the gestures? Also, would you recommend me to get this laptop in 2023 probably used or some other laptop for a hackintoshing?
