### ISSUE TITLE
dGPU acceleration got disabled for no reason

### ISSUE THREAD

**Issue by KristianApostolov** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#6]
The dGPU acceleration on my machine got disabled after booting in windows for 2 days instead of macOS.
For context I haven't updated any apps and my machine is the g14 with the ryzen 6800hs and rx 6800s.

**Comment by b00t0x** [comment]
check the MUX switch setting in Armoury Crate.

**Comment by KristianApostolov** [comment]
I was on eco, correct.
Do I need to go trough the whole process again or is it just going to work after I restore the stuff?

**Comment by b00t0x** [comment]
dGPU must be set primary in macOS.
