### ISSUE TITLE
PCIe device fix

### ISSUE THREAD

**Issue by ExtremeXT** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#9]
The new AMD Kernel Patches fixed the problem on MSI motherboards and Zen 4 motherboards, probably will on your laptop too. You can see the process here: https://forum.amd-osx.com/threads/ryzen-7000-testing.3318/post-24250
Note that your IOPCIFamilly replacement guide was really helpful in the debugging.

**Comment by b00t0x** [comment]
Thanks for telling me. I also think it works. I'll try it.

**Comment by b00t0x** [comment]
I confirmed the patch fixed the IOPCIFamily problem! ( fixed in #11 )
Thanks!

**Comment by ExtremeXT** [comment]
> I confirmed the patch fixed the IOPCIFamily problem! ( fixed in #11 ) Thanks!

Nice! About the other issues I also have ideas, do you have Discord or Telegram?

**Comment by b00t0x** [comment]
@extremegrief1 Thank you for your help. b00t0x#2250 in Discord, but I can't respond frequently because of English skills and timezone.
